name: Auto Push 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Make push to Prow-Scripts
      uses: redhat-chaos/actions/prow-scripts@main
      with:
        AUTOPUSH: ${{ secrets.AUTOPUSH }}